name: github-workflow CI

on: [push,pull_request]

jobs:
  grpc-proto-build:
    runs-on: ubuntu-latest
    steps: 
      - name: install dependencies
        run: |
          sudo apt install protobuf-compiler 
          go install github.com/golang/protobuf/protoc-gen-go@latest
      - name: Checkout
        uses: actions/checkout@v3
      - name: build-proto
        run: make proto
  go-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Go test
        run: make test